// flow-typed signature: a17bb3f92962ce307265c977dbddedba
// flow-typed version: <<STUB>>/@types/jest_v^20.0.7/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/jest' {
  declare module.exports: any;
}
