// flow-typed signature: 4ba957d09e779fc45a053375e270ac05
// flow-typed version: <<STUB>>/awesome-typescript-loader_v^3.2.3/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'awesome-typescript-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'awesome-typescript-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'awesome-typescript-loader/dist/cache' {
  declare module.exports: any;
}

declare module 'awesome-typescript-loader/dist/checker/checker' {
  declare module.exports: any;
}

declare module 'awesome-typescript-loader/dist/checker/fs' {
  declare module.exports: any;
}

declare module 'awesome-typescript-loader/dist/checker/index' {
  declare module.exports: any;
}

declare module 'awesome-typescript-loader/dist/checker/protocol' {
  declare module.exports: any;
}

declare module 'awesome-typescript-loader/dist/checker/runtime' {
  declare module.exports: any;
}

declare module 'awesome-typescript-loader/dist/checker/send' {
  declare module.exports: any;
}

declare module 'awesome-typescript-loader/dist/entry' {
  declare module.exports: any;
}

declare module 'awesome-typescript-loader/dist/helpers' {
  declare module.exports: any;
}

declare module 'awesome-typescript-loader/dist/index' {
  declare module.exports: any;
}

declare module 'awesome-typescript-loader/dist/instance' {
  declare module.exports: any;
}

declare module 'awesome-typescript-loader/dist/interfaces' {
  declare module.exports: any;
}

declare module 'awesome-typescript-loader/dist/paths-plugin' {
  declare module.exports: any;
}

declare module 'awesome-typescript-loader/dist/watch-mode' {
  declare module.exports: any;
}

// Filename aliases
declare module 'awesome-typescript-loader/dist/cache.js' {
  declare module.exports: $Exports<'awesome-typescript-loader/dist/cache'>;
}
declare module 'awesome-typescript-loader/dist/checker/checker.js' {
  declare module.exports: $Exports<'awesome-typescript-loader/dist/checker/checker'>;
}
declare module 'awesome-typescript-loader/dist/checker/fs.js' {
  declare module.exports: $Exports<'awesome-typescript-loader/dist/checker/fs'>;
}
declare module 'awesome-typescript-loader/dist/checker/index.js' {
  declare module.exports: $Exports<'awesome-typescript-loader/dist/checker/index'>;
}
declare module 'awesome-typescript-loader/dist/checker/protocol.js' {
  declare module.exports: $Exports<'awesome-typescript-loader/dist/checker/protocol'>;
}
declare module 'awesome-typescript-loader/dist/checker/runtime.js' {
  declare module.exports: $Exports<'awesome-typescript-loader/dist/checker/runtime'>;
}
declare module 'awesome-typescript-loader/dist/checker/send.js' {
  declare module.exports: $Exports<'awesome-typescript-loader/dist/checker/send'>;
}
declare module 'awesome-typescript-loader/dist/entry.js' {
  declare module.exports: $Exports<'awesome-typescript-loader/dist/entry'>;
}
declare module 'awesome-typescript-loader/dist/helpers.js' {
  declare module.exports: $Exports<'awesome-typescript-loader/dist/helpers'>;
}
declare module 'awesome-typescript-loader/dist/index.js' {
  declare module.exports: $Exports<'awesome-typescript-loader/dist/index'>;
}
declare module 'awesome-typescript-loader/dist/instance.js' {
  declare module.exports: $Exports<'awesome-typescript-loader/dist/instance'>;
}
declare module 'awesome-typescript-loader/dist/interfaces.js' {
  declare module.exports: $Exports<'awesome-typescript-loader/dist/interfaces'>;
}
declare module 'awesome-typescript-loader/dist/paths-plugin.js' {
  declare module.exports: $Exports<'awesome-typescript-loader/dist/paths-plugin'>;
}
declare module 'awesome-typescript-loader/dist/watch-mode.js' {
  declare module.exports: $Exports<'awesome-typescript-loader/dist/watch-mode'>;
}
declare module 'awesome-typescript-loader/index' {
  declare module.exports: $Exports<'awesome-typescript-loader'>;
}
declare module 'awesome-typescript-loader/index.js' {
  declare module.exports: $Exports<'awesome-typescript-loader'>;
}
