// flow-typed signature: 3025cc7b9003805111c3caea05f711e4
// flow-typed version: <<STUB>>/envalid_v^4.1.1/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'envalid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'envalid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'envalid/lib/reporter' {
  declare module.exports: any;
}

declare module 'envalid/lib/strictProxy' {
  declare module.exports: any;
}

declare module 'envalid/lib/validators' {
  declare module.exports: any;
}

// Filename aliases
declare module 'envalid/index' {
  declare module.exports: $Exports<'envalid'>;
}
declare module 'envalid/index.js' {
  declare module.exports: $Exports<'envalid'>;
}
declare module 'envalid/lib/reporter.js' {
  declare module.exports: $Exports<'envalid/lib/reporter'>;
}
declare module 'envalid/lib/strictProxy.js' {
  declare module.exports: $Exports<'envalid/lib/strictProxy'>;
}
declare module 'envalid/lib/validators.js' {
  declare module.exports: $Exports<'envalid/lib/validators'>;
}
