// flow-typed signature: cf0ba610b073f1bb90d51c773864af29
// flow-typed version: <<STUB>>/enzyme-react-16-adapter-setup_v^0.1.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'enzyme-react-16-adapter-setup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'enzyme-react-16-adapter-setup' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'enzyme-react-16-adapter-setup/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'enzyme-react-16-adapter-setup/dist/index.js' {
  declare module.exports: $Exports<'enzyme-react-16-adapter-setup/dist/index'>;
}
