// flow-typed signature: a7c3ca84ea251d0f5adbc68b08c097a0
// flow-typed version: <<STUB>>/eslint-plugin-jest_v^21.17.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-jest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-jest/build/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/build/rules/no-disabled-tests' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/build/rules/no-focused-tests' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/build/rules/no-identical-title' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/build/rules/types' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/build/rules/valid-expect' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-jest/build/index.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/build/index'>;
}
declare module 'eslint-plugin-jest/build/rules/no-disabled-tests.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/build/rules/no-disabled-tests'>;
}
declare module 'eslint-plugin-jest/build/rules/no-focused-tests.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/build/rules/no-focused-tests'>;
}
declare module 'eslint-plugin-jest/build/rules/no-identical-title.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/build/rules/no-identical-title'>;
}
declare module 'eslint-plugin-jest/build/rules/types.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/build/rules/types'>;
}
declare module 'eslint-plugin-jest/build/rules/valid-expect.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/build/rules/valid-expect'>;
}
