// flow-typed signature: 1f52b0af9171f2fed0d558f196d6c8bb
// flow-typed version: <<STUB>>/graphql-request_v^1.6.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-request'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-request' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-request/dist/src/index' {
  declare module.exports: any;
}

declare module 'graphql-request/dist/src/types' {
  declare module.exports: any;
}

declare module 'graphql-request/dist/tests/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-request/dist/src/index.js' {
  declare module.exports: $Exports<'graphql-request/dist/src/index'>;
}
declare module 'graphql-request/dist/src/types.js' {
  declare module.exports: $Exports<'graphql-request/dist/src/types'>;
}
declare module 'graphql-request/dist/tests/index.test.js' {
  declare module.exports: $Exports<'graphql-request/dist/tests/index.test'>;
}
