// flow-typed signature: d8c03f1eb04e620ac979e7e43cdd9ae6
// flow-typed version: <<STUB>>/mongoose-findoneorcreate_v^1.0.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mongoose-findoneorcreate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mongoose-findoneorcreate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mongoose-findoneorcreate/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mongoose-findoneorcreate/dist/index.js' {
  declare module.exports: $Exports<'mongoose-findoneorcreate/dist/index'>;
}
