// flow-typed signature: dea2076afe6f48c1ad137281f249b223
// flow-typed version: <<STUB>>/npm-scripts-watcher_v^1.0.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'npm-scripts-watcher'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'npm-scripts-watcher' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'npm-scripts-watcher/lib/watcher' {
  declare module.exports: any;
}

// Filename aliases
declare module 'npm-scripts-watcher/lib/watcher.js' {
  declare module.exports: $Exports<'npm-scripts-watcher/lib/watcher'>;
}
