// flow-typed signature: f3264d57c8e9ac263f15a2e089b2ab4f
// flow-typed version: <<STUB>>/react-form_v2.4/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-form'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-form' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-form/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-form/dist/index.js' {
  declare module.exports: $Exports<'react-form/dist/index'>;
}
