// flow-typed signature: 154ad7a0c8d660c1a42019527f9d3a99
// flow-typed version: <<STUB>>/seamless-immutable_v^7.1.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'seamless-immutable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'seamless-immutable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'seamless-immutable/seamless-immutable.development' {
  declare module.exports: any;
}

declare module 'seamless-immutable/seamless-immutable.development.min' {
  declare module.exports: any;
}

declare module 'seamless-immutable/seamless-immutable.production.min' {
  declare module.exports: any;
}

declare module 'seamless-immutable/src/seamless-immutable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'seamless-immutable/seamless-immutable.development.js' {
  declare module.exports: $Exports<'seamless-immutable/seamless-immutable.development'>;
}
declare module 'seamless-immutable/seamless-immutable.development.min.js' {
  declare module.exports: $Exports<'seamless-immutable/seamless-immutable.development.min'>;
}
declare module 'seamless-immutable/seamless-immutable.production.min.js' {
  declare module.exports: $Exports<'seamless-immutable/seamless-immutable.production.min'>;
}
declare module 'seamless-immutable/src/seamless-immutable.js' {
  declare module.exports: $Exports<'seamless-immutable/src/seamless-immutable'>;
}
