// flow-typed signature: 7b29f0a34ee9da4647d2623dd76405c5
// flow-typed version: <<STUB>>/styled-components-theme_v^1.0.5/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-components-theme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-components-theme' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-components-theme/dist/styled-components-theme' {
  declare module.exports: any;
}

declare module 'styled-components-theme/dist/styled-components-theme.min' {
  declare module.exports: any;
}

declare module 'styled-components-theme/es/__tests__/addModifier.spec' {
  declare module.exports: any;
}

declare module 'styled-components-theme/es/__tests__/decorateSelector.spec' {
  declare module.exports: any;
}

declare module 'styled-components-theme/es/__tests__/index.spec' {
  declare module.exports: any;
}

declare module 'styled-components-theme/es/__tests__/setup' {
  declare module.exports: any;
}

declare module 'styled-components-theme/es/addModifier' {
  declare module.exports: any;
}

declare module 'styled-components-theme/es/aliases' {
  declare module.exports: any;
}

declare module 'styled-components-theme/es/colorMethods' {
  declare module.exports: any;
}

declare module 'styled-components-theme/es/decorateSelector' {
  declare module.exports: any;
}

declare module 'styled-components-theme/es/index' {
  declare module.exports: any;
}

declare module 'styled-components-theme/es/makeThemeColor' {
  declare module.exports: any;
}

declare module 'styled-components-theme/lib/__tests__/addModifier.spec' {
  declare module.exports: any;
}

declare module 'styled-components-theme/lib/__tests__/decorateSelector.spec' {
  declare module.exports: any;
}

declare module 'styled-components-theme/lib/__tests__/index.spec' {
  declare module.exports: any;
}

declare module 'styled-components-theme/lib/addModifier' {
  declare module.exports: any;
}

declare module 'styled-components-theme/lib/aliases' {
  declare module.exports: any;
}

declare module 'styled-components-theme/lib/colorMethods' {
  declare module.exports: any;
}

declare module 'styled-components-theme/lib/decorateSelector' {
  declare module.exports: any;
}

declare module 'styled-components-theme/lib/index' {
  declare module.exports: any;
}

declare module 'styled-components-theme/lib/makeThemeColor' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-components-theme/dist/styled-components-theme.js' {
  declare module.exports: $Exports<'styled-components-theme/dist/styled-components-theme'>;
}
declare module 'styled-components-theme/dist/styled-components-theme.min.js' {
  declare module.exports: $Exports<'styled-components-theme/dist/styled-components-theme.min'>;
}
declare module 'styled-components-theme/es/__tests__/addModifier.spec.js' {
  declare module.exports: $Exports<'styled-components-theme/es/__tests__/addModifier.spec'>;
}
declare module 'styled-components-theme/es/__tests__/decorateSelector.spec.js' {
  declare module.exports: $Exports<'styled-components-theme/es/__tests__/decorateSelector.spec'>;
}
declare module 'styled-components-theme/es/__tests__/index.spec.js' {
  declare module.exports: $Exports<'styled-components-theme/es/__tests__/index.spec'>;
}
declare module 'styled-components-theme/es/__tests__/setup.js' {
  declare module.exports: $Exports<'styled-components-theme/es/__tests__/setup'>;
}
declare module 'styled-components-theme/es/addModifier.js' {
  declare module.exports: $Exports<'styled-components-theme/es/addModifier'>;
}
declare module 'styled-components-theme/es/aliases.js' {
  declare module.exports: $Exports<'styled-components-theme/es/aliases'>;
}
declare module 'styled-components-theme/es/colorMethods.js' {
  declare module.exports: $Exports<'styled-components-theme/es/colorMethods'>;
}
declare module 'styled-components-theme/es/decorateSelector.js' {
  declare module.exports: $Exports<'styled-components-theme/es/decorateSelector'>;
}
declare module 'styled-components-theme/es/index.js' {
  declare module.exports: $Exports<'styled-components-theme/es/index'>;
}
declare module 'styled-components-theme/es/makeThemeColor.js' {
  declare module.exports: $Exports<'styled-components-theme/es/makeThemeColor'>;
}
declare module 'styled-components-theme/lib/__tests__/addModifier.spec.js' {
  declare module.exports: $Exports<'styled-components-theme/lib/__tests__/addModifier.spec'>;
}
declare module 'styled-components-theme/lib/__tests__/decorateSelector.spec.js' {
  declare module.exports: $Exports<'styled-components-theme/lib/__tests__/decorateSelector.spec'>;
}
declare module 'styled-components-theme/lib/__tests__/index.spec.js' {
  declare module.exports: $Exports<'styled-components-theme/lib/__tests__/index.spec'>;
}
declare module 'styled-components-theme/lib/addModifier.js' {
  declare module.exports: $Exports<'styled-components-theme/lib/addModifier'>;
}
declare module 'styled-components-theme/lib/aliases.js' {
  declare module.exports: $Exports<'styled-components-theme/lib/aliases'>;
}
declare module 'styled-components-theme/lib/colorMethods.js' {
  declare module.exports: $Exports<'styled-components-theme/lib/colorMethods'>;
}
declare module 'styled-components-theme/lib/decorateSelector.js' {
  declare module.exports: $Exports<'styled-components-theme/lib/decorateSelector'>;
}
declare module 'styled-components-theme/lib/index.js' {
  declare module.exports: $Exports<'styled-components-theme/lib/index'>;
}
declare module 'styled-components-theme/lib/makeThemeColor.js' {
  declare module.exports: $Exports<'styled-components-theme/lib/makeThemeColor'>;
}
