// flow-typed signature: 7fa5d1ce456ae3118db280bcf70a75ce
// flow-typed version: <<STUB>>/swagger-ui-express_v^2.0.10/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'swagger-ui-express'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'swagger-ui-express' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'swagger-ui-express/static/swagger-ui-bundle' {
  declare module.exports: any;
}

declare module 'swagger-ui-express/static/swagger-ui-init' {
  declare module.exports: any;
}

declare module 'swagger-ui-express/static/swagger-ui-standalone-preset' {
  declare module.exports: any;
}

// Filename aliases
declare module 'swagger-ui-express/index' {
  declare module.exports: $Exports<'swagger-ui-express'>;
}
declare module 'swagger-ui-express/index.js' {
  declare module.exports: $Exports<'swagger-ui-express'>;
}
declare module 'swagger-ui-express/static/swagger-ui-bundle.js' {
  declare module.exports: $Exports<'swagger-ui-express/static/swagger-ui-bundle'>;
}
declare module 'swagger-ui-express/static/swagger-ui-init.js' {
  declare module.exports: $Exports<'swagger-ui-express/static/swagger-ui-init'>;
}
declare module 'swagger-ui-express/static/swagger-ui-standalone-preset.js' {
  declare module.exports: $Exports<'swagger-ui-express/static/swagger-ui-standalone-preset'>;
}
