// flow-typed signature: e96e868f083409b8ad35ef2fdcd14de1
// flow-typed version: <<STUB>>/swagger-jsdoc_v^1.9.7/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'swagger-jsdoc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'swagger-jsdoc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'swagger-jsdoc/bin/swagger-jsdoc' {
  declare module.exports: any;
}

declare module 'swagger-jsdoc/lib/index' {
  declare module.exports: any;
}

declare module 'swagger-jsdoc/lib/swagger-helpers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'swagger-jsdoc/bin/swagger-jsdoc.js' {
  declare module.exports: $Exports<'swagger-jsdoc/bin/swagger-jsdoc'>;
}
declare module 'swagger-jsdoc/index' {
  declare module.exports: $Exports<'swagger-jsdoc'>;
}
declare module 'swagger-jsdoc/index.js' {
  declare module.exports: $Exports<'swagger-jsdoc'>;
}
declare module 'swagger-jsdoc/lib/index.js' {
  declare module.exports: $Exports<'swagger-jsdoc/lib/index'>;
}
declare module 'swagger-jsdoc/lib/swagger-helpers.js' {
  declare module.exports: $Exports<'swagger-jsdoc/lib/swagger-helpers'>;
}
