// flow-typed signature: 991ee887999fff7c995a267dbf1f63ee
// flow-typed version: <<STUB>>/testcafe-browser-provider-nightmare_v^0.0.5/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'testcafe-browser-provider-nightmare'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'testcafe-browser-provider-nightmare' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'testcafe-browser-provider-nightmare/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'testcafe-browser-provider-nightmare/lib/index.js' {
  declare module.exports: $Exports<'testcafe-browser-provider-nightmare/lib/index'>;
}
