// flow-typed signature: a0987b63a894a835f3fd0651a3f7aab0
// flow-typed version: <<STUB>>/tslint-react_v^3.2.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tslint-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tslint-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tslint-react/rules/index' {
  declare module.exports: any;
}

declare module 'tslint-react/rules/jsxAlignmentRule' {
  declare module.exports: any;
}

declare module 'tslint-react/rules/jsxBanPropsRule' {
  declare module.exports: any;
}

declare module 'tslint-react/rules/jsxBooleanValueRule' {
  declare module.exports: any;
}

declare module 'tslint-react/rules/jsxCurlySpacingRule' {
  declare module.exports: any;
}

declare module 'tslint-react/rules/jsxEqualsSpacingRule' {
  declare module.exports: any;
}

declare module 'tslint-react/rules/jsxKeyRule' {
  declare module.exports: any;
}

declare module 'tslint-react/rules/jsxNoBindRule' {
  declare module.exports: any;
}

declare module 'tslint-react/rules/jsxNoLambdaRule' {
  declare module.exports: any;
}

declare module 'tslint-react/rules/jsxNoMultilineJsRule' {
  declare module.exports: any;
}

declare module 'tslint-react/rules/jsxNoStringRefRule' {
  declare module.exports: any;
}

declare module 'tslint-react/rules/jsxSelfCloseRule' {
  declare module.exports: any;
}

declare module 'tslint-react/rules/jsxUseTranslationFunctionRule' {
  declare module.exports: any;
}

declare module 'tslint-react/rules/jsxWrapMultilineRule' {
  declare module.exports: any;
}

declare module 'tslint-react/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tslint-react/rules/index.js' {
  declare module.exports: $Exports<'tslint-react/rules/index'>;
}
declare module 'tslint-react/rules/jsxAlignmentRule.js' {
  declare module.exports: $Exports<'tslint-react/rules/jsxAlignmentRule'>;
}
declare module 'tslint-react/rules/jsxBanPropsRule.js' {
  declare module.exports: $Exports<'tslint-react/rules/jsxBanPropsRule'>;
}
declare module 'tslint-react/rules/jsxBooleanValueRule.js' {
  declare module.exports: $Exports<'tslint-react/rules/jsxBooleanValueRule'>;
}
declare module 'tslint-react/rules/jsxCurlySpacingRule.js' {
  declare module.exports: $Exports<'tslint-react/rules/jsxCurlySpacingRule'>;
}
declare module 'tslint-react/rules/jsxEqualsSpacingRule.js' {
  declare module.exports: $Exports<'tslint-react/rules/jsxEqualsSpacingRule'>;
}
declare module 'tslint-react/rules/jsxKeyRule.js' {
  declare module.exports: $Exports<'tslint-react/rules/jsxKeyRule'>;
}
declare module 'tslint-react/rules/jsxNoBindRule.js' {
  declare module.exports: $Exports<'tslint-react/rules/jsxNoBindRule'>;
}
declare module 'tslint-react/rules/jsxNoLambdaRule.js' {
  declare module.exports: $Exports<'tslint-react/rules/jsxNoLambdaRule'>;
}
declare module 'tslint-react/rules/jsxNoMultilineJsRule.js' {
  declare module.exports: $Exports<'tslint-react/rules/jsxNoMultilineJsRule'>;
}
declare module 'tslint-react/rules/jsxNoStringRefRule.js' {
  declare module.exports: $Exports<'tslint-react/rules/jsxNoStringRefRule'>;
}
declare module 'tslint-react/rules/jsxSelfCloseRule.js' {
  declare module.exports: $Exports<'tslint-react/rules/jsxSelfCloseRule'>;
}
declare module 'tslint-react/rules/jsxUseTranslationFunctionRule.js' {
  declare module.exports: $Exports<'tslint-react/rules/jsxUseTranslationFunctionRule'>;
}
declare module 'tslint-react/rules/jsxWrapMultilineRule.js' {
  declare module.exports: $Exports<'tslint-react/rules/jsxWrapMultilineRule'>;
}
declare module 'tslint-react/utils.js' {
  declare module.exports: $Exports<'tslint-react/utils'>;
}
