// flow-typed signature: 24841881ebe0dd4a9c5582d2843230a1
// flow-typed version: <<STUB>>/tslint-loader_v^3.5.3/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tslint-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tslint-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tslint-loader/formatters/customFormatter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tslint-loader/formatters/customFormatter.js' {
  declare module.exports: $Exports<'tslint-loader/formatters/customFormatter'>;
}
declare module 'tslint-loader/index' {
  declare module.exports: $Exports<'tslint-loader'>;
}
declare module 'tslint-loader/index.js' {
  declare module.exports: $Exports<'tslint-loader'>;
}
