// flow-typed signature: 00a7fb0578c79ebdeeff2eb7036ffd00
// flow-typed version: <<STUB>>/webpack-dev-middleware-webpack-2_v^1.5.1/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-dev-middleware-webpack-2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-dev-middleware-webpack-2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-dev-middleware-webpack-2/middleware' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-dev-middleware-webpack-2/middleware.js' {
  declare module.exports: $Exports<'webpack-dev-middleware-webpack-2/middleware'>;
}
